// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcYmrVKueAy5P1S7ron0TgqjqbtfTI1nM',
    appId: '1:1078477800158:web:0030cc2c1147e1e0c4384f',
    messagingSenderId: '1078477800158',
    projectId: 'carebox-3d817',
    authDomain: 'carebox-3d817.firebaseapp.com',
    storageBucket: 'carebox-3d817.firebasestorage.app',
    measurementId: 'G-B3Z4NS63ZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2_KsIh9lmv0nRpxrmF4wI9kP9M089JZc',
    appId: '1:1078477800158:android:589a80ea073f886cc4384f',
    messagingSenderId: '1078477800158',
    projectId: 'carebox-3d817',
    storageBucket: 'carebox-3d817.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSiuDq9q4aIu0DEQkd3YUS0-kqxXrjkYQ',
    appId: '1:1078477800158:ios:fa90b4bc0cf3ef90c4384f',
    messagingSenderId: '1078477800158',
    projectId: 'carebox-3d817',
    storageBucket: 'carebox-3d817.firebasestorage.app',
    iosBundleId: 'com.example.carebox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSiuDq9q4aIu0DEQkd3YUS0-kqxXrjkYQ',
    appId: '1:1078477800158:ios:fa90b4bc0cf3ef90c4384f',
    messagingSenderId: '1078477800158',
    projectId: 'carebox-3d817',
    storageBucket: 'carebox-3d817.firebasestorage.app',
    iosBundleId: 'com.example.carebox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcYmrVKueAy5P1S7ron0TgqjqbtfTI1nM',
    appId: '1:1078477800158:web:25f8e1aac1ff5db7c4384f',
    messagingSenderId: '1078477800158',
    projectId: 'carebox-3d817',
    authDomain: 'carebox-3d817.firebaseapp.com',
    storageBucket: 'carebox-3d817.firebasestorage.app',
    measurementId: 'G-VVF1018K7X',
  );
}
